version: '3.8'

services:
  db:
    image: postgres:13
    container_name: odontosoft_db
    environment:
      POSTGRES_DB: odontosoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5433:5432"
    volumes:
      - odontosoft:/var/lib/postgresql/data
      - C:/Users/PERSONAL/Documents/Proyectos/OdontoSoftFullStack/OdontoSoftBack/src/main/resources/script.sql:/docker-entrypoint-initdb.d/script.sql

  backend:
    build: ./odontosoftback
    container_name: odontosoft_backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/odontosoft
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerty
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - ./odontosoftback:/app
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]

  frontend:
    build: ./odontosoftfront
    container_name: odontosoft_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./odontosoftfront:/app
    working_dir: /app
    command: ["npm", "start"]

volumes:
  odontosoft: